import { Noto_Serif } from "next/font/google";
import "./global.css";
import { Metadata } from "next/types";
import { Header } from "@/app/components/Header";
import { Footer } from "@/app/components/Footer";

const inter = Noto_Serif({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
